pipeline {
    agent any

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile') {
            agent {
                docker {
                    image 'gradle:7.6.6-jdk17'
                    reuseNode true
                }
            }
            steps {
                dir('03-cd/exercises/jenkins-resources/calculator') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew compileJava'
                }
            }
        }

        stage('Unit Tests') {
            agent {
                docker {
                    image 'gradle:7.6.6-jdk17'
                    reuseNode true
                }
            }
            steps {
                dir('03-cd/exercises/jenkins-resources/calculator') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew test'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true,
                         testResults: '03-cd/exercises/jenkins-resources/calculator/build/test-results/test/*.xml'
                }
            }
        }
    }

    post {
        always {
            sh 'rm -rf 03-cd/exercises/jenkins-resources/calculator/build || true'
        }
    }
}
